swagger: "2.0"

info: 
  version: 1.0.0
  title: Shopping List App API
  description: A simple shopping list application to order your gorcery.

schemes:
  - http
host: localhost:8080
basePath: /api/v1

paths:
  /cart:
    get:
      summary: Gets Cart's Products and Total
      description: Returns the cart details (products and total).
      responses:
        200:
          description: Cart's products and total.
          schema:
            $ref: "#/definitions/Cart"
            
    post:
      summary: Adds Product To Cart
      description: Adds new product to cart.
      pramaters:
        - name: product_id
          in: body
          type: number
          required: true
          description: The product's ID
        - name: product_quantity
          in: body
          type: number
          required: true
          description: The product's quantity
      responses:
        201:
          description: Product was added successfully to cart.
          schema:
            $ref: "#/definitions/Cart"
        422:
          description: Parameters validation failed.
          schema:
            $ref: "#/definitions/Error"
        400:
          description:
            Product is not available in the ProductsList. ||
            Product is out of stock. ||
            Available quantity is less than order quantity.
          schema:
            $ref: "#/definitions/Message"
            

  /cart/{id}:
    get:
      summary: Gets a product
      description: Returns a single product for its unique ID
      parameters:
        - name: id
          in: path
          required: true
          description: The product's ID
          type: number
      responses:
        200:
          description: A Product
          schema:
            $ref: "#/definitions/Product"
        404:
          description: The Product does not exists in the shopping cart.
          schema:
            $ref: "#/definitions/Message"

    put:
      summary: Updates a Product's Quantity
      description: Updates a single product's quantity
      parameters:
        - name: id
          in: path
          required: true
          description: The product's ID
          type: number
        - name: product_quantity
          in: body
          type: number
          required: true
          description: The product's quantity
      responses:
        202:
          description: Returns the shopping cart after updating a product's quantity.
          schema:
            $ref: "#/definitions/Cart"
        422:
          description: Parameters validation failed.
          schema:
            $ref: "#/definitions/Error"
        400:
          description:
            Product is out of stock. ||
            Available quantity is less than order quantity.
          schema:
            $ref: "#/definitions/Message"
        404:
          description: The Product does not exists in the shopping cart.
          schema:
            $ref: "#/definitions/Message"

    delete:
      summary: Deletes a product
      description: Deletes a single product for its unique ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The product's ID
          type: number
      responses:
        202:
          description: Returns the deleted product.
          schema:
            $ref: "#/definitions/Product"

  /products:
    get:
      summary: Gets A List of Available Products
      description: Returns a list of available products
      responses:
        200:
          description: List of available products
          schema:
            $ref: "#/definitions/Products"

    post:
      summary: Adds New Product To ProductsList.
      description: Adds new product to productsList.
      pramaters:
        - name: product_id
          in: body
          type: number
          required: true
          description: The product's ID

        - name: product_name
          in: body
          type: string
          required: true
          description: The product's name

        - name: product_price
          in: body
          type: number
          required: true
          description: The product's price

        - name: product_quantity
          in: body
          type: number
          required: true
          description: The product's quantity
      responses:
        201:
          description: Returns the newly created product.
          schema:
            $ref: "#/definitions/Product"
        422:
          description: Parameters validation failed.
          schema:
            $ref: "#/definitions/Error"

  /products/{id}:
    get:
      summary: Gets a product
      description: Returns a single product for its unique ID
      parameters:
        - name: id
          in: path
          required: true
          type: number
          description: The product's ID
      responses:
        200:
          description: A Product
          schema:
            $ref: "#/definitions/Product"
        404:
          description: Product not found
          schema:
            $ref: "#/definitions/Message"

    put:
      summary: Updates An Existing Product
      description: Updates an existing product.
      pramaters:
        - name: product_id
          in: path
          type: number
          required: true
          description: The product's ID

        - name: product_name
          in: body
          type: string
          description: The product's name

        - name: product_price
          in: body
          type: number
          description: The product's price

        - name: product_quantity
          in: body
          type: number
          description: The product's quantity

      responses:
        200:
          description: Returns the updated product
          schema:
            $ref: "#/definitions/Product"
        404:
          description: Product not found
          schema:
            $ref: "#/definitions/Message"

    delete:
      summary: Deletes An Existing Product
      description: Deletes an existing product.
      pramaters:
        - name: product_id
          in: path
          type: number
          required: true
          description: The product's ID

      responses:
        200:
          description: Returns the deleted product
          schema:
            $ref: "#/definitions/Product"
        404:
          description: Product not found
          schema:
            $ref: "#/definitions/Message"


# ### DEFINITIONS ###
definitions:
  Cart:
    required:
      - products
      - total
    properties:
      products:
        $ref: "#/definitions/Products"
      total:
        type: number

  Products:
    type: array
    items:
      $ref: "#/definitions/Product"
  
  Product:
    required:
      - product_id
      - product_name
      - product_price
      - product_quantity
    properties:
      product_id:
        type: number
      product_name:
        type: string
      product_price:
        type: number
      product_quantity:
        type: number

  Message:
    required:
      - message
    properties:
      message:
        type: string

  Error:
    required:
      - error
    properties:
      message:
        type: string
# ### ### ### ### ### ###